const content = document.querySelector("#content");

// We create the element in a hierarchy as we would on the HTML
const div = document.createElement("div");
const h2 = document.createElement("h2");
const p = document.createElement("p");

// Now, let's attach each one with the appropriate element that comes in a higher hierarchy sorting

// We start by attaching the h2 and the p to the div
div.appendChild(h2);
div.appendChild(p);

// Then, we attach the div to the container element (content) to see the results on the page
content.appendChild(div);

// Finally, we give each element it's text content so we can see it
h2.textContent = "Some heading generated by JavaScript!";
p.textContent = "Some paragraph generated by JavaScript!";
