// Targeting the container
const content = document.querySelector("#content");

// Creating the paragraph
const paragraph = document.createElement("p");

// Giving it some content, some text in this example
paragraph.textContent =
  "This is a paragraph generated by JavaScript on runtime!";

// Now, we should attach this paragraph to the container element so we can see it on the page
content.appendChild(paragraph);
